/*
 * Méthodes utilitaires
 */

// Méthode traitant les erreurs générées par Axios
function axiosCatchError(e)
{
    alert("Une erreur s'est produite")
    console.log(e)
}